README.md

Fișierul conține momentan pașii de instalare.

docs(readme): adaugă pagina

---

.github/Contribute.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

PR-ul adauga templates pentru:
- Pull Requests
- Issues
- Ghid pentru contributii

Contribute guidelines & templates

---

package.json
src/app/app.module.ts
src/declarations.d.ts
src/index.html
src/models/marker-voting-station.ts
src/pages/map/map.ts
src/providers/markers.ts

- instalează google map MarkerClusterer
- adaugă markers[] cu secțiile de votare dintr-un json parțial

feat(pages/map): adaugă markers

---

src/app/app.module.ts
src/pages/map/map.ts
src/pages/news/news.ts
src/providers/markers.ts
src/providers/news.ts
src/providers/position.ts

- update ionic RC3 - Error Reporting
- refactor pages/map - observable
- refactor pages/news - mută constructor în metode + subscribe/unsubscribe

refactor(pages/map|news), update ionic RC3

---

src/app/app.component.ts
src/index.html
src/pages/map/map.html
src/pages/news/news.html
src/pages/news/news.ts
src/providers/markers.ts
src/providers/news.ts

- fix(pages/news/news): publică membru folosit în template
- ssl google maps
- puțină ordine prin private vs public
- aranjează cod ici/colo
`ionic serve` / `ionic upload` / `ionic emulate android` / `ionic run android`, văzut, testat

fix: erori AoT & style

---

src/app/app.component.ts
src/app/app.module.ts
src/pages/info/info.html
src/pages/info/info.ts

Pagina de info generale pentru alegeri (urmeaza si faq)
`ionic serve`

feat(pages/info): adaugă pagina de informații

---

src/app/app.component.ts
src/app/app.module.ts

Pastram sectiunea de stiri, dar nu este valabila pentru launch
ionic serve

feat(pages/news): ascunde pagina de stiri pana pe 12 dec

---

package.json
src/app/app.component.ts
src/app/app.module.ts
src/pages/faq/faq-items.ts
src/pages/faq/faq.html
src/pages/faq/faq.scss
src/pages/faq/faq.ts

Adaugat pagina de intrebari frecvente

feat(pages/faq): adaugă pagina de intrebari frecvente

---

src/app/app.component.ts
src/app/app.module.ts
src/pages/feedback/feedback.html
src/pages/feedback/feedback.scss
src/pages/feedback/feedback.ts

Slider "Opinia ta"
- primul slide cu descriere (f. pe scurt)
- trei slide-uri cu intrebari da/nu
- un slide cu multumiri si share pe social media
Momentan nu se fac requesturi in backend si copy-ul este doar placeholder
ionic serve

feat(pages/feedback): adaugă pagina de feedback

---

src/theme/variables.scss

Repară path-ul pentru logoul svg.
`ionic upload`, `ionic emulate android`, văzut

fix(theme): path logo

---

src/pages/map-view/map-view.html
src/pages/map-view/map-view.ts

feat(page/map-view): adauga buton pentru link spre feedback

---

config.xml
package.json
src/app/app.module.ts
src/pages/feedback/feedback.html
src/pages/feedback/feedback.ts

Daca utilizatorul a raspuns deja la intrebare, nu mai afisa intrebarea
ionic serve

feat(page/feedback) Cere doar odata feedback

---

src/app/app.component.ts

Icon de harta pentru harta, checkbox pentru feedback
ionic serve

feat(sidebar): Schimbat icons in ceva mai rezonabil

---

config.xml
src/pages/map-view/map-view.html
src/pages/map-view/map-view.ts
src/pages/map/map.ts

Adaugat buton care sa deschida aplicatia de harti de pe telefon cu ruta pana la sectia de vot selectata.
```
ionic build android
adb install -r -d .../android-debug.apk
```
si `ionic serve` pentru web

feat(page/map-view): Optiune de vizualizare ruta pana la sectie

---

src/theme/variables.scss

Ordin de la design
ionic serve

fix(header): Resize logo

---

src/pages/feedback/feedback.html
src/pages/map-view/map-view.html

Update copy cu ce am primit de la Ligia
ionic serve

fix(page/feedback): Update copy 

---

src/pages/map/map.html
src/pages/map/map.scss
src/pages/map/map.ts

Adauga un hint pe pagina cu harta, care apare o singura data pana cand e apasat "inchide"
ionic serve

feat(page/map): Toast intro

---

src/app/app.component.ts
src/app/app.module.ts
src/pages/faq/faq.html
src/pages/info/info.html
src/pages/info/info.scss
src/pages/info/info.ts

De la stakeholders ording: 
- O singura pagina de "resurse"
- Link spre FAQ de aici 
- Link spre alte locuri utile pe minunatul internet
- Credits
ionic serve

feat(page/info): Bring back the info page

---

src/app/app.html
src/pages/faq/faq.html
src/pages/feedback/feedback.html
src/pages/info/info.html
src/pages/map-view/map-view.html
src/pages/map/map.html
src/pages/news/news.html

- mută meniul înapoi în stânga
`ionic serve`, văzut

feat(ion-header): meniu, logo/titlu, acțiuni

---

src/pages/map/map.ts

Ascunde toast definitiv on dismiss
eyes

fix(pages/map): Fix toast cache

---

config.xml
src/pages/map/map.ts

Icon-ul rezultat in urma cautarii manuale ar trebui sa fie user-location.png

fix(pages/map): Schimba icon-ul pentru rezultat search box 

---

config.xml

Pregatire pentru release:
- Actualizare descriere si contact autor
- Bump version number
`ionic run build`

config(config.xml): Update details and bump version number

---

src/index.html
src/pages/welcome/welcome.html
src/pages/welcome/welcome.scss
src/pages/welcome/welcome.ts
src/theme/variables.scss

- scoate texte / css aferent
- mută storage.set în promise
- șterge whitespaces
- lang="ro" în index.html
`ionic run android`, `ionic emulate android`

refactor(pages/welcome): scoate texte

---

.gitignore

res/ e generat, nu are ce cauta in .git
yolo

config(gitignore): Ignore res/ dir

---

src/pages/map/map.ts

Atunci cand user-ul a share-uit locatia:
- Gseste cele mai apropiate N markere
- Seteaza centrul hartii si nivelul de zoom in asa fel incat sa afiseze si locatia user-ului, si markerele selectate
`ionic run android`

feat(pages/map): Center map on user location and show closest markers

---

config.xml
package.json
src/app/app.component.ts
src/pages/faq/faq.ts
src/pages/feedback/feedback.ts
src/pages/info/info.ts
src/pages/map-view/map-view.ts
src/pages/map/map.ts
src/pages/news/news.ts
src/pages/welcome/welcome.ts

- instalează analytics
- adaugă cod de tracking pe fiecare pagină
Rulat `ionic run android` și în paralel dashboard analytics deschis pe Real-Time.

feat(pages): adaugă analytics

---

src/theme/variables.scss

Logo-ul din burger menu nu e responsive ceea ce e o problema pe device-uri cu rezolutia mai mica. 
`ionic run browser`

fix(theme/variables.scss): Responsive logo

---

package.json

Actualizare:
- descriere
- licenta
- homepage
- bugs
- versiune
eyes

fix(docs): README

---

src/providers/markers.ts

Import-uri lipsa
`ionic build`

fix(providers/markers): Fix imports

---

src/app/app.component.ts
src/models/marker-voting-station.ts
src/pages/feedback/feedback.html
src/pages/feedback/feedback.ts
src/pages/info/info.ts
src/pages/map-view/map-view.ts
src/pages/map/map.html
src/pages/map/map.scss
src/pages/map/map.ts
src/pages/welcome/welcome.ts
src/providers/markers.ts

- catch errors pe pluginurile cordova care returnau erori
- curăță white spaces
`ionic serve`, `ionic emulate android`, `ionic run android`

fix: ionic serve
